# Shared by the Spire build and the standalone reified-deps build.
scalaVersion=3.10.1-RC1-bin-SNAPSHOT-nonbootstrapped
libraryVersion=3.10.1-RC1-bin-SNAPSHOT
catsKernelVersion=2.9.0-reified-SNAPSHOT
algebraVersion=2.9.0-reified-SNAPSHOT
